"""Tier 2: Agentic user journey verification.

Tests whether multi-step user flows work end-to-end. The output of
step 1 feeds into step 2. This catches integration bugs that
per-endpoint Tier 1 probes miss.

Two modes:
- sequential (default): API/CLI calls in sequence. Cheaper, faster.
- browser: real browser via chrome-devtools MCP. Catches visual/UX bugs.

Example journey Tier 1 can't test:
  1. Register user → get user ID
  2. Login with that user → get session
  3. Browse products → pick a product ID
  4. Add product to cart → verify cart has item
  5. Checkout → verify order created
  6. View order history → verify order appears

Each step depends on the previous step's output. If step 3 fails,
steps 4-6 can't run. That's the "journey" — a connected flow.
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import requests

from otto.certifier.adapter import TestConfig
from otto.certifier.binder import BoundAuth, BoundJourney, BoundPlan, BoundStep
from otto.certifier.intent_compiler import RequirementMatrix
from otto.certifier.journey_compiler import JourneyMatrix, JourneySpec
from otto.observability import append_text_log

logger = logging.getLogger("otto.certifier.tier2")


@dataclass
class StepProof:
    """Evidence for a single journey step."""
    timestamp: str = ""
    request: dict[str, Any] = field(default_factory=dict)   # method, url, body
    response: dict[str, Any] = field(default_factory=dict)   # status, body (truncated)


@dataclass
class JourneyStep:
    action: str
    detail: str
    passed: bool
    data: dict[str, Any] = field(default_factory=dict)  # output for next step
    error: str = ""
    proof: StepProof = field(default_factory=StepProof)


@dataclass
class JourneyResult:
    name: str
    description: str
    passed: bool
    steps: list[JourneyStep]
    stopped_at: str = ""  # which step broke the flow


@dataclass
class Tier2Result:
    product_dir: str
    intent: str
    base_url: str
    journeys_tested: int
    journeys_passed: int
    journeys_failed: int
    journeys: list[JourneyResult]
    cost_usd: float = 0.0
    duration_s: float = 0.0
    mode: str = "sequential"

    def journey_score(self) -> str:
        if self.journeys_tested == 0:
            return "n/a"
        return f"{self.journeys_passed}/{self.journeys_tested} ({round(self.journeys_passed / self.journeys_tested * 100)}%)"

    def step_score(self) -> str:
        total = sum(len(j.steps) for j in self.journeys)
        passed = sum(sum(1 for s in j.steps if s.passed) for j in self.journeys)
        if total == 0:
            return "n/a"
        return f"{passed}/{total} ({round(passed / total * 100)}%)"

    def score(self) -> str:
        """Combined score showing both journey and step level."""
        return f"Journeys: {self.journey_score()}, Steps: {self.step_score()}"


def _tier2_log(project_dir: Path, *lines: str) -> None:
    append_text_log(project_dir / "certifier-reports" / "tier2.log", lines)


def run_tier2_from_journeys(
    journey_matrix: JourneyMatrix,
    test_config: TestConfig,
    base_url: str,
    project_dir: Path,
) -> Tier2Result:
    """Run Tier 2 using compiled journey specs. The primary entry point.

    Journeys are generated by the journey compiler from the intent.
    Each journey is executed as a sequence of HTTP calls.
    """
    start_time = time.monotonic()

    _tier2_log(
        project_dir,
        f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] Tier 2 from compiled journeys",
        f"base_url: {base_url}",
        f"journeys: {len(journey_matrix.journeys)}",
    )

    results = []
    for spec in journey_matrix.journeys:
        result = _execute_journey_spec(spec, test_config, base_url)
        results.append(result)

    duration_s = round(time.monotonic() - start_time, 1)
    passed = sum(1 for j in results if j.passed)

    tier2_result = Tier2Result(
        product_dir=str(project_dir),
        intent=journey_matrix.intent,
        base_url=base_url,
        journeys_tested=len(results),
        journeys_passed=passed,
        journeys_failed=len(results) - passed,
        journeys=results,
        duration_s=duration_s,
        mode="compiled",
    )

    report_dir = project_dir / "certifier-reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    save_tier2_report(tier2_result, report_dir / "tier2-report.json")

    _tier2_log(project_dir, f"Tier 2 done: {tier2_result.score()}, {duration_s}s")
    return tier2_result


def run_tier2_from_bound_plan(
    bound_plan: BoundPlan,
    base_url: str,
    project_dir: Path,
) -> Tier2Result:
    """Run Tier 2 using a pre-bound journey plan."""

    start_time = time.monotonic()
    _tier2_log(
        project_dir,
        f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] Tier 2 from bound plan",
        f"base_url: {base_url}",
        f"journeys: {len(bound_plan.journeys)}",
    )

    results = []
    for journey in bound_plan.journeys:
        results.append(_execute_bound_journey(journey, base_url))

    duration_s = round(time.monotonic() - start_time, 1)
    passed = sum(1 for item in results if item.passed)
    tier2_result = Tier2Result(
        product_dir=str(project_dir),
        intent=bound_plan.intent,
        base_url=base_url,
        journeys_tested=len(results),
        journeys_passed=passed,
        journeys_failed=len(results) - passed,
        journeys=results,
        duration_s=duration_s,
        mode="bound",
    )

    report_dir = project_dir / "certifier-reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    save_tier2_report(tier2_result, report_dir / "tier2-report.json")

    _tier2_log(project_dir, f"Tier 2 done: {tier2_result.score()}, {duration_s}s")
    return tier2_result


def _execute_bound_journey(journey: BoundJourney, base_url: str) -> JourneyResult:
    session = requests.Session()
    steps: list[JourneyStep] = []
    variables: dict[str, Any] = {}
    current_auth: BoundAuth | None = None

    for bound_step in journey.steps:
        action = bound_step.action

        if action == "register":
            step = _exec_bound_register(session, base_url, bound_step, variables)
            if step.passed and bound_step.auth:
                current_auth = bound_step.auth
        elif action == "login":
            step = _exec_bound_login(session, base_url, bound_step, variables)
            if step.passed and bound_step.auth:
                current_auth = bound_step.auth
        elif action == "login_admin":
            step = _exec_bound_login(session, base_url, bound_step, variables)
            if step.passed and bound_step.auth:
                current_auth = bound_step.auth
        elif action in {"get", "post", "put", "patch", "delete"}:
            step = _exec_bound_http(session, base_url, bound_step, variables, current_auth)
        elif action in {"verify", "verify_contains"}:
            step = _exec_verify(bound_step.step, variables)
        elif action in {"verify_count", "verify_min"}:
            step = _exec_verify_count(bound_step.step, variables)
        elif action == "fresh_session":
            session = requests.Session()
            current_auth = None
            step = JourneyStep(action="fresh_session", detail="new unauthenticated session", passed=True)
        else:
            step = JourneyStep(
                action=action,
                detail=f"unknown action: {action}",
                passed=False,
                error=f"unsupported action: {action}",
            )

        if step.data and step.passed:
            save_as = bound_step.step.get("save_as")
            if save_as:
                variables[save_as] = step.data
            _extract_ids(step.data, variables)

        steps.append(step)
        critical_actions = {"register", "login", "login_admin", "post", "put", "patch", "delete"}
        if not step.passed and action in critical_actions:
            return JourneyResult(
                name=journey.name,
                description=journey.description,
                passed=False,
                steps=steps,
                stopped_at=action,
            )

    passed_steps = sum(1 for item in steps if item.passed)
    all_passed = passed_steps == len(steps)
    return JourneyResult(
        name=journey.name,
        description=journey.description,
        passed=all_passed,
        steps=steps,
        stopped_at="" if all_passed else f"{passed_steps}/{len(steps)} steps passed",
    )


def _exec_bound_register(
    session: requests.Session,
    base_url: str,
    bound_step: BoundStep,
    variables: dict[str, Any],
) -> JourneyStep:
    route = bound_step.resolved_route
    if not route:
        return JourneyStep(action="register", detail="no bound register route", passed=False, error="route not bound")

    body = _bound_body(bound_step, variables)
    auth = bound_step.auth
    if auth:
        body = dict(body or {})
        body.setdefault("email", auth.email)
        body.setdefault("password", auth.password)
        if auth.name:
            body.setdefault("name", auth.name)

    url = f"{base_url}{_render_string(route, variables)}"
    try:
        response = session.post(url, json=body, timeout=10)
    except Exception as exc:
        return JourneyStep(action="register", detail=str(exc), passed=False, error=str(exc))

    payload = _safe_json(response)
    if response.status_code in (200, 201, 409):
        return JourneyStep(
            action="register",
            detail=f"POST {route} → {response.status_code}",
            passed=True,
            data=payload if response.status_code != 409 else {"email": (auth.email if auth else body.get("email"))},
            proof=StepProof(
                timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                request={"method": "POST", "url": url, "body": _redact_password(body)},
                response={"status": response.status_code, "body": payload or {"text": response.text[:200]}},
            ),
        )
    return JourneyStep(
        action="register",
        detail=f"POST {route} → {response.status_code}",
        passed=False,
        error=f"expected [200, 201, 409], got {response.status_code}",
        proof=StepProof(
            timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            request={"method": "POST", "url": url, "body": _redact_password(body)},
            response={"status": response.status_code, "body": payload or {"text": response.text[:200]}},
        ),
    )


def _exec_bound_login(
    session: requests.Session,
    base_url: str,
    bound_step: BoundStep,
    variables: dict[str, Any],
) -> JourneyStep:
    auth = bound_step.auth
    if auth is None:
        return JourneyStep(action="login", detail="missing bound auth", passed=False, error="bound auth missing")

    ok, detail, proof = _ensure_bound_session(session, base_url, bound_step, variables, auth)
    return JourneyStep(
        action=bound_step.action or "login",
        detail=detail,
        passed=ok,
        error="" if ok else detail,
        proof=proof,
    )


def _exec_bound_http(
    session: requests.Session,
    base_url: str,
    bound_step: BoundStep,
    variables: dict[str, Any],
    current_auth: BoundAuth | None,
) -> JourneyStep:
    method = bound_step.method or bound_step.action.upper()
    route = bound_step.resolved_route
    if not route:
        return JourneyStep(
            action=f"{method} ?",
            detail="no bound route",
            passed=False,
            error="route not bound",
        )

    auth = bound_step.auth or current_auth
    if auth and (bound_step.requires_auth or bound_step.requires_admin):
        ok, detail, proof = _ensure_bound_session(session, base_url, bound_step, variables, auth)
        if not ok:
            return JourneyStep(
                action=f"{method} {route}",
                detail=detail,
                passed=False,
                error=detail,
                proof=proof,
            )

    rendered_route = _render_string(route, variables)
    if "{{" in rendered_route:
        return JourneyStep(
            action=f"{method} {route}",
            detail="variable not resolved",
            passed=False,
            error=f"unresolved variables in path: {route}",
        )

    body = _bound_body(bound_step, variables)
    expect = bound_step.step.get("expect_status", [200] if method == "GET" else [200, 201])
    if isinstance(expect, int):
        expect = [expect]

    kwargs: dict[str, Any] = {"timeout": 10}
    if body and method != "GET":
        kwargs["json"] = body
    try:
        response = session.request(method, f"{base_url}{rendered_route}", **kwargs)
    except Exception as exc:
        return JourneyStep(
            action=f"{method} {rendered_route}",
            detail=str(exc),
            passed=False,
            error=str(exc),
        )

    payload = _safe_json(response)
    if response.status_code in expect:
        response_data = _unwrap_tier2_payload(payload) if payload is not None else {}
        response_preview = payload if payload is not None else {"text": response.text[:200]}
        return JourneyStep(
            action=f"{method} {rendered_route}",
            detail=str(response.status_code),
            passed=True,
            data=response_data,
            proof=StepProof(
                timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                request={"method": method, "url": f"{base_url}{rendered_route}", "body": body},
                response={"status": response.status_code, "body": response_preview},
            ),
        )

    return JourneyStep(
        action=f"{method} {rendered_route}",
        detail=f"HTTP {response.status_code}",
        passed=False,
        error=f"expected {expect}, got {response.status_code}",
        proof=StepProof(
            timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            request={"method": method, "url": f"{base_url}{rendered_route}", "body": body},
            response={"status": response.status_code, "body": payload if payload is not None else {"text": response.text[:200]}},
        ),
    )


def _ensure_bound_session(
    session: requests.Session,
    base_url: str,
    bound_step: BoundStep,
    variables: dict[str, Any],
    auth: BoundAuth,
) -> tuple[bool, str, StepProof]:
    if auth.mechanism == "nextauth":
        return _ensure_bound_nextauth_session(session, base_url, bound_step, auth)
    return _ensure_bound_generic_session(session, base_url, bound_step, variables, auth)


def _ensure_bound_nextauth_session(
    session: requests.Session,
    base_url: str,
    bound_step: BoundStep,
    auth: BoundAuth,
) -> tuple[bool, str, StepProof]:
    csrf_route = auth.csrf_route or "/api/auth/csrf"
    login_route = auth.login_route or bound_step.resolved_route or "/api/auth/callback/credentials"
    csrf_url = f"{base_url}{csrf_route}"
    try:
        csrf_response = session.get(csrf_url, timeout=10)
        csrf_payload = csrf_response.json()
        csrf_token = csrf_payload.get("csrfToken", "")
    except Exception as exc:
        proof = StepProof(
            timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            request={"method": "GET", "url": csrf_url},
            response={"error": str(exc)},
        )
        return False, f"failed CSRF request: {exc}", proof

    callback_url = f"{base_url}{login_route}"
    request_body = {
        "email": auth.email,
        "password": auth.password,
        "csrfToken": csrf_token,
        "redirect": "false",
        "json": "true",
    }
    try:
        response = session.post(callback_url, data=request_body, timeout=10, allow_redirects=False)
    except Exception as exc:
        proof = StepProof(
            timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            request={"method": "POST", "url": callback_url, "body": _redact_password(request_body)},
            response={"error": str(exc)},
        )
        return False, f"credentials callback failed: {exc}", proof

    cookie_names = set(session.cookies.keys())
    session_cookie = cookie_names & {
        "next-auth.session-token",
        "__Secure-next-auth.session-token",
        "authjs.session-token",
        "__Secure-authjs.session-token",
    }
    if session_cookie:
        proof = StepProof(
            timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            request={"method": "POST", "url": callback_url, "body": _redact_password(request_body)},
            response={"status": response.status_code, "body": _safe_json(response) or {"text": response.text[:200]}},
        )
        return True, f"NextAuth session active for {auth.email}", proof

    try:
        session_response = session.get(f"{base_url}/api/auth/session", timeout=5)
        session_payload = session_response.json()
    except Exception:
        session_payload = None
    if session_payload and session_payload.get("user"):
        proof = StepProof(
            timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            request={"method": "POST", "url": callback_url, "body": _redact_password(request_body)},
            response={"status": response.status_code, "body": _safe_json(response) or {"text": response.text[:200]}},
        )
        return True, f"NextAuth session active for {auth.email}", proof

    proof = StepProof(
        timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
        request={"method": "POST", "url": callback_url, "body": _redact_password(request_body)},
        response={"status": response.status_code, "body": _safe_json(response) or {"text": response.text[:200]}},
    )
    return False, f"NextAuth login failed with HTTP {response.status_code}", proof


def _ensure_bound_generic_session(
    session: requests.Session,
    base_url: str,
    bound_step: BoundStep,
    variables: dict[str, Any],
    auth: BoundAuth,
) -> tuple[bool, str, StepProof]:
    login_route = auth.login_route or bound_step.resolved_route
    if not login_route:
        proof = StepProof(timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"))
        return False, "bound auth did not include a login route", proof

    request_body = {
        "email": auth.email,
        "password": auth.password,
    }
    for request_style in ("json", "data"):
        kwargs: dict[str, Any] = {"timeout": 10, "allow_redirects": False}
        if request_style == "json":
            kwargs["json"] = request_body
        else:
            kwargs["data"] = request_body
        try:
            response = session.post(f"{base_url}{login_route}", **kwargs)
        except Exception as exc:
            proof = StepProof(
                timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                request={"method": "POST", "url": f"{base_url}{login_route}", "body": _redact_password(request_body)},
                response={"error": str(exc)},
            )
            continue

        if response.status_code in (200, 201, 202, 204, 302, 303):
            payload = _safe_json(response)
            if isinstance(payload, dict):
                token = payload.get("token") or payload.get("accessToken") or payload.get("access_token")
                if token:
                    variables["auth_token"] = token
                    session.headers["Authorization"] = f"Bearer {token}"
            proof = StepProof(
                timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                request={"method": "POST", "url": f"{base_url}{login_route}", "body": _redact_password(request_body)},
                response={"status": response.status_code, "body": payload or {"text": response.text[:200]}},
            )
            return True, f"{login_route} accepted bound credentials with HTTP {response.status_code}", proof

    proof = StepProof(
        timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
        request={"method": "POST", "url": f"{base_url}{login_route}", "body": _redact_password(request_body)},
        response={"error": "all login attempts failed"},
    )
    return False, "all login attempts failed", proof


def _bound_body(bound_step: BoundStep, variables: dict[str, Any]) -> Any:
    return _render_template(bound_step.resolved_body, variables)


def _safe_json(response: requests.Response) -> Any:
    try:
        return response.json()
    except Exception:
        return None


def _redact_password(body: Any) -> Any:
    if not isinstance(body, dict):
        return body
    redacted = dict(body)
    if "password" in redacted:
        redacted["password"] = "***"
    return redacted


def _execute_journey_spec(
    spec: JourneySpec,
    config: TestConfig,
    base_url: str,
) -> JourneyResult:
    """Execute a single compiled journey spec."""
    session = requests.Session()
    steps: list[JourneyStep] = []
    variables: dict[str, Any] = {}

    for step_spec in spec.steps:
        action = step_spec.get("action", "")

        if action == "register":
            step = _exec_register(session, base_url, config, step_spec)
        elif action == "login":
            step = _exec_login(session, base_url, config, step_spec)
        elif action == "login_admin":
            admin = config.admin_user()
            if admin:
                step = _exec_login(session, base_url, config, {"email": admin.email, "password": admin.password})
            else:
                step = JourneyStep(action="login_admin", detail="no admin credentials", passed=False, error="adapter found no admin user")
        elif action == "get":
            step = _exec_http(session, base_url, "GET", step_spec, variables, config)
        elif action == "post":
            step = _exec_http(session, base_url, "POST", step_spec, variables, config)
        elif action == "put":
            step = _exec_http(session, base_url, "PUT", step_spec, variables, config)
        elif action == "delete":
            step = _exec_http(session, base_url, "DELETE", step_spec, variables, config)
        elif action in ("verify", "verify_contains"):
            step = _exec_verify(step_spec, variables)
        elif action in ("verify_count", "verify_min"):
            step = _exec_verify_count(step_spec, variables)
        elif action == "fresh_session":
            session = requests.Session()
            step = JourneyStep(action="fresh_session", detail="new unauthenticated session", passed=True)
        else:
            step = JourneyStep(action=action, detail=f"unknown action: {action}", passed=False, error=f"unsupported action: {action}")

        # Save output to variables
        if step.data and step.passed:
            save_as = step_spec.get("save_as")
            if save_as:
                variables[save_as] = step.data

            # Auto-extract common IDs for variable substitution
            _extract_ids(step.data, variables)

        steps.append(step)

        # Stop journey if a CRITICAL step fails (auth, core action)
        # Non-critical steps (verify, get) record failure but continue
        critical_actions = {"register", "login", "login_admin", "post", "put", "delete"}
        if not step.passed and action in critical_actions:
            return JourneyResult(
                name=spec.name, description=spec.description,
                passed=False, steps=steps, stopped_at=action,
            )

    passed_steps = sum(1 for s in steps if s.passed)
    all_passed = passed_steps == len(steps)
    return JourneyResult(
        name=spec.name, description=spec.description,
        passed=all_passed, steps=steps,
        stopped_at="" if all_passed else f"{passed_steps}/{len(steps)} steps passed",
    )


def _exec_register(session: requests.Session, base_url: str, config: TestConfig, step: dict[str, Any]) -> JourneyStep:
    email = step.get("email", f"journey-{int(time.time())}@test.com")
    password = step.get("password", "JourneyTest123!")
    name = step.get("name", "Journey Test User")

    for path in [config.register_endpoint] + config.register_candidates + ["/api/auth/register", "/api/register"]:
        if not path:
            continue
        try:
            r = session.post(f"{base_url}{path}", json={"email": email, "password": password, "name": name}, timeout=10)
            if r.status_code in (200, 201, 409):
                resp_body = {}
                try: resp_body = r.json()
                except Exception: pass
                return JourneyStep(
                    action="register", detail=f"POST {path} → {r.status_code}",
                    passed=True, data=resp_body if r.status_code != 409 else {"email": email},
                    proof=StepProof(
                        timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                        request={"method": "POST", "url": f"{base_url}{path}", "body": {"email": email, "password": "***", "name": name}},
                        response={"status": r.status_code, "body": resp_body},
                    ),
                )
        except Exception:
            continue
    return JourneyStep(action="register", detail="registration failed", passed=False, error="no register endpoint responded")


def _exec_login(session: requests.Session, base_url: str, config: TestConfig, step: dict[str, Any]) -> JourneyStep:
    email = step.get("email", "")
    password = step.get("password", "")

    if config.auth_type == "nextauth":
        try:
            csrf = session.get(f"{base_url}/api/auth/csrf", timeout=10).json().get("csrfToken", "")
            r = session.post(f"{base_url}/api/auth/callback/credentials", data={
                "email": email, "password": password,
                "csrfToken": csrf, "redirect": "false", "json": "true",
            }, timeout=10, allow_redirects=False)
            # Check for session cookie — name varies by NextAuth version and config
            cookie_names = set(session.cookies.keys())
            session_cookie = cookie_names & {
                "next-auth.session-token",
                "__Secure-next-auth.session-token",
                "authjs.session-token",
                "__Secure-authjs.session-token",
            }
            if session_cookie:
                return JourneyStep(action="login", detail=f"NextAuth login as {email}", passed=True)
            # Fallback: check if /api/auth/session returns a user
            try:
                sess_resp = session.get(f"{base_url}/api/auth/session", timeout=5)
                if sess_resp.status_code == 200:
                    sess_data = sess_resp.json()
                    if sess_data and sess_data.get("user"):
                        return JourneyStep(action="login", detail=f"NextAuth session active for {email}", passed=True)
            except Exception:
                pass
        except Exception as e:
            return JourneyStep(action="login", detail=str(e), passed=False, error=str(e))

    for path in ["/api/auth/login", "/api/login"]:
        try:
            r = session.post(f"{base_url}{path}", json={"email": email, "password": password}, timeout=10)
            if r.status_code in (200, 201):
                return JourneyStep(action="login", detail=f"POST {path} → {r.status_code}", passed=True)
        except Exception:
            continue
    return JourneyStep(action="login", detail=f"login failed for {email}", passed=False, error="could not authenticate")


def _exec_http(session: requests.Session, base_url: str, method: str, step: dict[str, Any], variables: dict[str, Any], test_config: TestConfig | None = None) -> JourneyStep:
    paths = step.get("candidate_paths", [step.get("path", "")])
    body = _render_template(step.get("body"), variables)
    expect = step.get("expect_status", [200] if method == "GET" else [200, 201])
    if isinstance(expect, int):
        expect = [expect]

    # Aliases for common patterns
    me_aliases = {"/api/auth/me", "/api/me", "/api/user/profile", "/api/users/me"}
    if any(p in me_aliases for p in paths):
        paths = list(paths) + ["/api/auth/session"]

    last_status = None
    last_error_text = ""
    self_heal_note = ""
    for path in paths:
        if not path:
            continue
        rendered_path = _render_string(path, variables)
        # Skip paths with unresolved {{variables}}
        if "{{" in rendered_path:
            continue
        url = f"{base_url}{rendered_path}"
        try:
            kwargs: dict[str, Any] = {"timeout": 10}
            if body and method != "GET":
                kwargs["json"] = body
            r = session.request(method, url, **kwargs)
            last_status = r.status_code
            # Self-heal: if 400 mentions valid values, retry with correction
            if r.status_code == 400 and body and method in ("PUT", "POST", "PATCH"):
                error_text = r.text[:500]
                last_error_text = error_text
                # Enum case fix: "Must be one of: PENDING, PAID, SHIPPED"
                enum_match = re.search(r"[Mm]ust be one of[:\s]+([A-Z_,\s]+)", error_text)
                if enum_match and isinstance(body, dict):
                    valid_values = [v.strip() for v in enum_match.group(1).split(",")]
                    for field, val in body.items():
                        if isinstance(val, str):
                            upper = val.upper()
                            if upper in valid_values and upper != val:
                                corrected_body = {**body, field: upper}
                                r2 = session.request(method, url, json=corrected_body, timeout=10)
                                if r2.status_code in expect:
                                    r = r2
                                    last_status = r2.status_code
                                    self_heal_note = " (self-healed: enum case)"
                                    break
            if r.status_code in expect:
                response_data: Any = {}
                try:
                    raw = r.json()
                    response_data = _unwrap_tier2_payload(raw)
                except Exception:
                    pass
                response_body_preview = {}
                try:
                    response_body_preview = r.json()
                    if isinstance(response_body_preview, (dict, list)):
                        preview_str = json.dumps(response_body_preview)
                        if len(preview_str) > 500:
                            response_body_preview = {"preview": preview_str[:500] + "..."}
                except Exception:
                    response_body_preview = {"text": r.text[:200]}

                return JourneyStep(
                    action=f"{method} {rendered_path}", detail=f"{r.status_code}{self_heal_note}",
                    passed=True, data=response_data,
                    proof=StepProof(
                        timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                        request={"method": method, "url": url, "body": body},
                        response={"status": r.status_code, "body": response_body_preview},
                    ),
                )
        except Exception:
            continue

    # Self-heal: inject adapter-discovered routes when all candidates fail with 404.
    # The journey compiler may guess wrong paths (e.g., /api/admin/products when the
    # app uses POST /api/products with requireAdmin middleware). The adapter already
    # scanned the code and knows the real routes.
    if last_status == 404 and test_config:
        adapter_paths = _find_adapter_routes(paths, method, test_config)
        for adapter_path in adapter_paths:
            rendered = _render_string(adapter_path, variables)
            if "{{" in rendered:
                continue
            url = f"{base_url}{rendered}"
            try:
                kwargs_fb: dict[str, Any] = {"timeout": 10}
                if body and method != "GET":
                    kwargs_fb["json"] = body
                r = session.request(method, url, **kwargs_fb)
                if r.status_code in expect:
                    response_data = {}
                    try:
                        raw = r.json()
                        response_data = raw if isinstance(raw, dict) else {}
                    except Exception:
                        pass
                    return JourneyStep(
                        action=f"{method} {rendered}", detail=f"{r.status_code} (adapter route)",
                        passed=True, data=response_data,
                        proof=StepProof(
                            timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                            request={"method": method, "url": url, "body": body},
                            response={"status": r.status_code, "body": {}},
                        ),
                    )
            except Exception:
                continue

    # Check if ALL paths had unresolved variables
    resolved_paths = [p for p in paths if "{{" not in _render_string(p, variables)]
    if not resolved_paths:
        unresolved = [p for p in paths if "{{" in _render_string(p, variables)]
        return JourneyStep(
            action=f"{method} {paths[0] if paths else '?'}",
            detail=f"variable not resolved",
            passed=False,
            error=f"unresolved variables in path: {unresolved[0] if unresolved else '?'}",
        )

    return JourneyStep(
        action=f"{method} {paths[0] if paths else '?'}",
        detail=f"no endpoint responded (last: {last_status})",
        passed=False,
        error=f"expected {expect}, tried {len(resolved_paths)} path(s)",
    )


def _find_adapter_routes(
    tried_paths: list[str],
    method: str,
    test_config: TestConfig,
) -> list[str]:
    """Find adapter-discovered routes that match the intent of the tried paths.

    Uses keyword extraction from the tried paths to find matching routes in the
    adapter's route inventory. Same approach as Tier 1's route injection.
    """
    # Extract keywords from the paths we tried
    keywords: set[str] = set()
    for path in tried_paths:
        for segment in path.lower().strip("/").split("/"):
            if segment and segment not in {"api", "v1", "v2", "auth"}:
                keywords.add(segment)

    # Find adapter routes matching those keywords
    matches = []
    already_tried = {p.lower().rstrip("/") for p in tried_paths}
    for route in test_config.routes:
        if method.upper() not in route.methods:
            continue
        if route.path.lower().rstrip("/") in already_tried:
            continue
        route_lower = route.path.lower()
        if any(kw in route_lower for kw in keywords):
            matches.append(route.path)

    return matches


def _exec_verify(step: dict[str, Any], variables: dict[str, Any]) -> JourneyStep:
    source_name = step.get("source", "")
    contains = step.get("contains", "")
    source_data = variables.get(source_name, {})
    source_str = json.dumps(source_data).lower()
    rendered_contains = _render_string(str(contains), variables).lower()

    found = rendered_contains in source_str
    return JourneyStep(
        action=f"verify '{contains}' in {source_name}",
        detail=f"{'found' if found else 'NOT found'}",
        passed=found,
        error="" if found else f"'{contains}' not in {source_name}",
    )


def _exec_verify_count(step: dict[str, Any], variables: dict[str, Any]) -> JourneyStep:
    source_name = step.get("source", "")
    min_count = step.get("min", 1)
    source_data = variables.get(source_name, {})

    # Count items
    if isinstance(source_data, list):
        count = len(source_data)
    elif isinstance(source_data, dict):
        items = source_data.get("items") or source_data.get("data") or []
        count = len(items) if isinstance(items, list) else (1 if source_data else 0)
    else:
        count = 0

    passed = count >= min_count
    return JourneyStep(
        action=f"verify {source_name} has ≥{min_count} items",
        detail=f"count={count}",
        passed=passed,
        error="" if passed else f"expected ≥{min_count}, got {count}",
    )


def _is_ecommerce_app(config: TestConfig) -> bool:
    """Return True when adapter signals indicate a commerce product."""
    if any("cart" in model.lower() for model in config.resource_models):
        return True

    ecommerce_keywords = ("cart", "checkout", "product", "products")
    return any(
        any(keyword in route.path.lower() for keyword in ecommerce_keywords)
        for route in config.routes
    )


def _extract_ids(data: Any, variables: dict[str, Any]) -> None:
    """Extract generic IDs from response data for variable substitution."""
    if isinstance(data, list):
        for item in data:
            if isinstance(item, dict) and item.get("id"):
                variables["first_item_id"] = str(item["id"])
                return
        return

    if isinstance(data, dict):
        if "id" in data and data["id"]:
            the_id = str(data["id"])
            variables["last_id"] = the_id
            variables["last_created_id"] = the_id

        import re as _re
        for val in data.values():
            if isinstance(val, str) and "orderId=" in val:
                m = re.search(r"orderId=([^&\s]+)", val)
                if m:
                    oid = m.group(1)
                    for alias in ("order_id", "customer_order_id", "new_order_id"):
                        if alias not in variables:
                            variables[alias] = oid

        items = data.get("items") or data.get("data") or []
        if isinstance(items, list):
            for item in items:
                if isinstance(item, dict) and item.get("id"):
                    variables["first_item_id"] = str(item["id"])
                    break


def _unwrap_tier2_payload(payload: Any) -> Any:
    if isinstance(payload, dict):
        for wrapper in ("data", "results", "items", "records"):
            value = payload.get(wrapper)
            if isinstance(value, (dict, list)):
                return value
    return payload


def _render_template(obj: Any, variables: dict[str, Any]) -> Any:
    """Replace {{variable}} placeholders in nested structures."""
    if obj is None:
        return None
    if isinstance(obj, str):
        return _render_string(obj, variables)
    if isinstance(obj, dict):
        return {k: _render_template(v, variables) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_render_template(v, variables) for v in obj]
    return obj


def _render_string(s: str, variables: dict[str, Any]) -> str:
    """Replace {{variable}} in a string."""
    import re
    def replace(match: re.Match) -> str:
        key = match.group(1)
        return str(variables.get(key, match.group(0)))
    return re.sub(r'\{\{(\w+)\}\}', replace, s)


def run_tier2_sequential(
    test_config: TestConfig,
    base_url: str,
    project_dir: Path,
    matrix: RequirementMatrix | None = None,
) -> Tier2Result:
    """Run Tier 2 sequential journey tests. No LLM needed.

    Journeys are derived from claims in the matrix (if provided)
    plus standard flows based on adapter-discovered features.
    """
    start_time = time.monotonic()

    _tier2_log(
        project_dir,
        f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] Tier 2 sequential started",
        f"base_url: {base_url}",
    )

    journeys = []
    is_ecommerce = _is_ecommerce_app(test_config)

    # Core journeys based on adapter-discovered features
    if is_ecommerce and (test_config.register_endpoint or any("cart" in model.lower() for model in test_config.resource_models)):
        journeys.append(_test_shopping_journey(test_config, base_url))

    if is_ecommerce and test_config.admin_user():
        journeys.append(_test_admin_journey(test_config, base_url))

    # Always test error handling
    journeys.append(_test_error_journey(test_config, base_url))

    # Additional journeys from matrix claims (features not covered above)
    if matrix:
        extra = _derive_extra_journeys(matrix, test_config, base_url)
        journeys.extend(extra)

    duration_s = round(time.monotonic() - start_time, 1)
    passed = sum(1 for j in journeys if j.passed)

    result = Tier2Result(
        product_dir=str(project_dir),
        intent="",
        base_url=base_url,
        journeys_tested=len(journeys),
        journeys_passed=passed,
        journeys_failed=len(journeys) - passed,
        journeys=journeys,
        duration_s=duration_s,
        mode="sequential",
    )

    # Save reports
    report_dir = project_dir / "certifier-reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    save_tier2_report(result, report_dir / "tier2-report.json")

    _tier2_log(
        project_dir,
        f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] Tier 2 done: {result.score()}, {duration_s}s",
    )

    return result


# ---------------------------------------------------------------------------
# Journey: Shopping flow (register → browse → cart → checkout → order history)
# ---------------------------------------------------------------------------

def _test_shopping_journey(config: TestConfig, base_url: str) -> JourneyResult:
    steps: list[JourneyStep] = []
    session = requests.Session()
    flow_data: dict[str, Any] = {}

    # Step 1: Register
    email = f"tier2-{int(time.time())}@eval.test"
    step = _step_register(session, base_url, config, email)
    steps.append(step)
    if not step.passed:
        return JourneyResult(
            name="Shopping Flow", description="Register → browse → cart → checkout → orders",
            passed=False, steps=steps, stopped_at="register",
        )

    # Step 2: Login
    step = _step_login(session, base_url, config, email)
    steps.append(step)
    if not step.passed:
        return JourneyResult(
            name="Shopping Flow", description="Register → browse → cart → checkout → orders",
            passed=False, steps=steps, stopped_at="login",
        )

    # Step 3: Browse products, pick one
    step = _step_browse_products(session, base_url)
    steps.append(step)
    if not step.passed:
        return JourneyResult(
            name="Shopping Flow", description="Register → browse → cart → checkout → orders",
            passed=False, steps=steps, stopped_at="browse",
        )
    flow_data["product_id"] = step.data.get("product_id")
    flow_data["product_name"] = step.data.get("product_name")
    flow_data["product_price"] = step.data.get("product_price")

    # Step 4: Add to cart
    step = _step_add_to_cart(session, base_url, flow_data["product_id"])
    steps.append(step)
    if not step.passed:
        return JourneyResult(
            name="Shopping Flow", description="Register → browse → cart → checkout → orders",
            passed=False, steps=steps, stopped_at="add_to_cart",
        )

    # Step 5: View cart, verify product is there
    step = _step_view_cart(session, base_url, flow_data["product_name"])
    steps.append(step)
    if not step.passed:
        return JourneyResult(
            name="Shopping Flow", description="Register → browse → cart → checkout → orders",
            passed=False, steps=steps, stopped_at="view_cart",
        )

    # Step 6: Checkout
    step = _step_checkout(session, base_url)
    steps.append(step)
    if not step.passed:
        return JourneyResult(
            name="Shopping Flow", description="Register → browse → cart → checkout → orders",
            passed=False, steps=steps, stopped_at="checkout",
        )
    flow_data["order_id"] = step.data.get("order_id")

    # Step 7: View order history, verify order appears
    step = _step_view_orders(session, base_url, flow_data.get("order_id"))
    steps.append(step)

    all_passed = all(s.passed for s in steps)
    return JourneyResult(
        name="Shopping Flow", description="Register → browse → cart → checkout → orders",
        passed=all_passed, steps=steps,
        stopped_at="" if all_passed else steps[-1].action,
    )


def _step_register(session: requests.Session, base_url: str, config: TestConfig, email: str) -> JourneyStep:
    for path in [config.register_endpoint] + config.register_candidates + ["/api/auth/register", "/api/register", "/api/signup"]:
        if not path:
            continue
        try:
            r = session.post(f"{base_url}{path}", json={
                "email": email, "password": "Tier2Test123!", "name": "Tier 2 Test User",
            }, timeout=10)
            if r.status_code in (200, 201):
                return JourneyStep(
                    action="register", detail=f"POST {path} → {r.status_code}",
                    passed=True, data={"email": email, "user": r.json()},
                )
        except Exception:
            continue
    return JourneyStep(action="register", detail="no registration endpoint responded", passed=False, error="registration failed on all endpoints")


def _step_login(session: requests.Session, base_url: str, config: TestConfig, email: str) -> JourneyStep:
    if config.auth_type == "nextauth":
        try:
            csrf_r = session.get(f"{base_url}/api/auth/csrf", timeout=10)
            csrf = csrf_r.json().get("csrfToken", "")
            r = session.post(f"{base_url}/api/auth/callback/credentials", data={
                "email": email, "password": "Tier2Test123!",
                "csrfToken": csrf, "redirect": "false", "json": "true",
            }, timeout=10, allow_redirects=False)
            if "next-auth.session-token" in dict(session.cookies):
                return JourneyStep(action="login", detail=f"NextAuth login → session established", passed=True)
        except Exception as e:
            return JourneyStep(action="login", detail=str(e), passed=False, error=str(e))

    for path in ["/api/auth/login", "/api/login"]:
        try:
            r = session.post(f"{base_url}{path}", json={
                "email": email, "password": "Tier2Test123!",
            }, timeout=10)
            if r.status_code in (200, 201):
                return JourneyStep(action="login", detail=f"POST {path} → {r.status_code}", passed=True)
        except Exception:
            continue

    return JourneyStep(action="login", detail="login failed", passed=False, error="could not establish session")


def _step_browse_products(session: requests.Session, base_url: str) -> JourneyStep:
    for path in ["/api/products", "/api/catalog"]:
        try:
            r = session.get(f"{base_url}{path}", timeout=10)
            if r.status_code == 200:
                data = r.json()
                products = data if isinstance(data, list) else data.get("data") or data.get("products") or []
                if products and isinstance(products, list) and len(products) > 0:
                    p = products[0]
                    return JourneyStep(
                        action="browse_products",
                        detail=f"GET {path} → {len(products)} products. Picked: {p.get('name', '?')} (${p.get('price', '?')})",
                        passed=True,
                        data={"product_id": p.get("id"), "product_name": p.get("name"), "product_price": p.get("price")},
                    )
        except Exception:
            continue
    return JourneyStep(action="browse_products", detail="no products found", passed=False, error="product catalog empty or unreachable")


def _step_add_to_cart(session: requests.Session, base_url: str, product_id: str) -> JourneyStep:
    for path in ["/api/cart", "/api/cart/items"]:
        try:
            r = session.post(f"{base_url}{path}", json={"productId": product_id, "quantity": 1}, timeout=10)
            if r.status_code in (200, 201):
                return JourneyStep(
                    action="add_to_cart",
                    detail=f"POST {path} → {r.status_code}. Product {product_id} added.",
                    passed=True,
                )
        except Exception:
            continue
    return JourneyStep(action="add_to_cart", detail="add to cart failed", passed=False, error="no cart endpoint accepted the request")


def _step_view_cart(session: requests.Session, base_url: str, expected_product: str | None) -> JourneyStep:
    for path in ["/api/cart", "/api/cart/items"]:
        try:
            r = session.get(f"{base_url}{path}", timeout=10)
            if r.status_code == 200:
                data = r.json()
                items = data if isinstance(data, list) else data.get("data") or data.get("items") or data.get("cart") or []
                if items and isinstance(items, list) and len(items) > 0:
                    product_found = not expected_product or any(
                        expected_product.lower() in json.dumps(item).lower() for item in items
                    )
                    return JourneyStep(
                        action="view_cart",
                        detail=f"GET {path} → {len(items)} item(s). Product {'found' if product_found else 'NOT found'}.",
                        passed=product_found,
                        error="" if product_found else f"expected '{expected_product}' in cart but not found",
                    )
        except Exception:
            continue
    return JourneyStep(action="view_cart", detail="cart empty or unreachable", passed=False, error="could not read cart")


def _step_checkout(session: requests.Session, base_url: str) -> JourneyStep:
    body = {
        "shippingAddress": {
            "name": "Tier 2 Test", "address": "123 Test St",
            "city": "Testville", "state": "CA", "zip": "90210", "country": "US",
        },
    }
    for path in ["/api/checkout", "/api/orders/checkout", "/api/payments"]:
        try:
            r = session.post(f"{base_url}{path}", json=body, timeout=10)
            if r.status_code in (200, 201):
                data = r.json()
                order_id = None
                # Extract order ID from various response shapes
                for key_path in [["data", "orderId"], ["data", "id"], ["orderId"], ["id"], ["order", "id"]]:
                    obj = data
                    for k in key_path:
                        if isinstance(obj, dict):
                            obj = obj.get(k)
                        else:
                            obj = None
                            break
                    if obj:
                        order_id = str(obj)
                        break

                warning = ""
                if isinstance(data, dict):
                    warning = data.get("warning", "")

                detail = f"POST {path} → {r.status_code}. Order: {order_id or 'unknown'}."
                if warning:
                    detail += f" Warning: {warning}"

                return JourneyStep(
                    action="checkout", detail=detail, passed=True,
                    data={"order_id": order_id},
                    error=warning if "not configured" in warning.lower() else "",
                )
        except Exception:
            continue
    return JourneyStep(action="checkout", detail="checkout failed", passed=False, error="no checkout endpoint accepted the request")


def _step_view_orders(session: requests.Session, base_url: str, expected_order_id: str | None) -> JourneyStep:
    for path in ["/api/orders", "/api/user/orders"]:
        try:
            r = session.get(f"{base_url}{path}", timeout=10)
            if r.status_code == 200:
                data = r.json()
                orders = data if isinstance(data, list) else data.get("data") or data.get("orders") or []
                if isinstance(orders, list):
                    order_found = not expected_order_id or any(
                        str(o.get("id", "")) == expected_order_id for o in orders
                    )
                    return JourneyStep(
                        action="view_orders",
                        detail=f"GET {path} → {len(orders)} order(s). New order {'found' if order_found else 'NOT found'}.",
                        passed=order_found,
                        error="" if order_found else f"order {expected_order_id} not in history",
                    )
        except Exception:
            continue
    return JourneyStep(action="view_orders", detail="orders unreachable", passed=False, error="could not read order history")


# ---------------------------------------------------------------------------
# Journey: Admin management
# ---------------------------------------------------------------------------

def _test_admin_journey(config: TestConfig, base_url: str) -> JourneyResult:
    steps: list[JourneyStep] = []
    session = requests.Session()
    admin = config.admin_user()

    if not admin:
        return JourneyResult(
            name="Admin Flow", description="Login as admin → create product → view orders",
            passed=False, steps=[JourneyStep(action="admin_login", detail="no admin credentials", passed=False, error="adapter found no admin user")],
            stopped_at="admin_login",
        )

    # Step 1: Login as admin
    step = _step_login(session, base_url, config, admin.email)
    # Override: use admin password
    if config.auth_type == "nextauth":
        session2 = requests.Session()
        try:
            csrf = session2.get(f"{base_url}/api/auth/csrf", timeout=10).json().get("csrfToken", "")
            session2.post(f"{base_url}/api/auth/callback/credentials", data={
                "email": admin.email, "password": admin.password,
                "csrfToken": csrf, "redirect": "false", "json": "true",
            }, timeout=10, allow_redirects=False)
            if "next-auth.session-token" in dict(session2.cookies):
                session = session2
                step = JourneyStep(action="admin_login", detail=f"Logged in as {admin.email} (admin)", passed=True)
        except Exception:
            pass

    steps.append(step)
    if not step.passed:
        return JourneyResult(
            name="Admin Flow", description="Login as admin → create product → view orders",
            passed=False, steps=steps, stopped_at="admin_login",
        )

    # Step 2: Create product
    product_data = {"name": "Tier2 Admin Test Product", "description": "Created by certifier", "price": 42.99, "stock": 10, "category": "Test"}
    step = _step_admin_create_product(session, base_url, product_data)
    steps.append(step)

    # Step 3: View orders
    step = _step_admin_view_orders(session, base_url)
    steps.append(step)

    all_passed = all(s.passed for s in steps)
    return JourneyResult(
        name="Admin Flow", description="Login as admin → create product → view orders",
        passed=all_passed, steps=steps,
    )


def _step_admin_create_product(session: requests.Session, base_url: str, product: dict[str, Any]) -> JourneyStep:
    for path in ["/api/products", "/api/admin/products"]:
        try:
            r = session.post(f"{base_url}{path}", json=product, timeout=10)
            if r.status_code in (200, 201):
                data = r.json()
                created = data.get("data") or data
                return JourneyStep(
                    action="admin_create_product",
                    detail=f"POST {path} → {r.status_code}. Created: {created.get('name', '?')} (${created.get('price', '?')})",
                    passed=True, data={"product": created},
                )
        except Exception:
            continue
    return JourneyStep(action="admin_create_product", detail="create product failed", passed=False, error="no product endpoint accepted the request")


def _step_admin_view_orders(session: requests.Session, base_url: str) -> JourneyStep:
    for path in ["/api/orders", "/api/admin/orders"]:
        try:
            r = session.get(f"{base_url}{path}", timeout=10)
            if r.status_code == 200:
                data = r.json()
                orders = data if isinstance(data, list) else data.get("data") or data.get("orders") or []
                if isinstance(orders, list):
                    return JourneyStep(
                        action="admin_view_orders",
                        detail=f"GET {path} → {len(orders)} order(s)",
                        passed=True,
                    )
        except Exception:
            continue
    return JourneyStep(action="admin_view_orders", detail="orders unreachable", passed=False, error="could not read orders as admin")


# ---------------------------------------------------------------------------
# Journey: Error handling
# ---------------------------------------------------------------------------

def _test_error_journey(config: TestConfig, base_url: str) -> JourneyResult:
    steps: list[JourneyStep] = []

    # Step 1: 404 page
    try:
        r = requests.get(f"{base_url}/nonexistent-page-tier2-test", timeout=10)
        steps.append(JourneyStep(
            action="404_page",
            detail=f"GET /nonexistent → {r.status_code}",
            passed=r.status_code == 404,
            error="" if r.status_code == 404 else f"expected 404, got {r.status_code}",
        ))
    except Exception as e:
        steps.append(JourneyStep(action="404_page", detail=str(e), passed=False, error=str(e)))

    # Step 2: Wrong login credentials
    session = requests.Session()
    if config.auth_type == "nextauth":
        try:
            csrf = session.get(f"{base_url}/api/auth/csrf", timeout=10).json().get("csrfToken", "")
            r = session.post(f"{base_url}/api/auth/callback/credentials", data={
                "email": "wrong@wrong.com", "password": "wrongpassword",
                "csrfToken": csrf, "redirect": "false", "json": "true",
            }, timeout=10, allow_redirects=False)
            # Should NOT have session token
            has_session = "next-auth.session-token" in dict(session.cookies)
            steps.append(JourneyStep(
                action="wrong_credentials",
                detail=f"Login with wrong creds → {'session established (BAD!)' if has_session else 'rejected (correct)'}",
                passed=not has_session,
                error="wrong credentials accepted!" if has_session else "",
            ))
        except Exception as e:
            steps.append(JourneyStep(action="wrong_credentials", detail=str(e), passed=False, error=str(e)))

    # Step 3: Access protected endpoint without auth
    fresh = requests.Session()
    try:
        r = fresh.get(f"{base_url}/api/cart", timeout=10)
        steps.append(JourneyStep(
            action="unauthenticated_access",
            detail=f"GET /api/cart without auth → {r.status_code}",
            passed=r.status_code in (401, 403),
            error="" if r.status_code in (401, 403) else f"expected 401/403, got {r.status_code}",
        ))
    except Exception as e:
        steps.append(JourneyStep(action="unauthenticated_access", detail=str(e), passed=False, error=str(e)))

    all_passed = all(s.passed for s in steps)
    return JourneyResult(
        name="Error Handling", description="404, wrong credentials, unauthorized access",
        passed=all_passed, steps=steps,
    )


# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------

def _derive_extra_journeys(
    matrix: RequirementMatrix,
    config: TestConfig,
    base_url: str,
) -> list[JourneyResult]:
    """Derive additional journeys from uncovered matrix claims."""
    if not _is_ecommerce_app(config):
        return []

    extra: list[JourneyResult] = []

    # Search/filter journey — if catalog claims mention search
    has_search = any("search" in c.id.lower() or "filter" in c.id.lower() for c in matrix.claims)
    if has_search:
        extra.append(_test_search_journey(config, base_url))

    # Data persistence journey — verify state survives across sessions
    has_persistence = any("persist" in c.id.lower() or "history" in c.id.lower() for c in matrix.claims)
    if has_persistence:
        extra.append(_test_persistence_journey(config, base_url))

    return extra


def _test_search_journey(config: TestConfig, base_url: str) -> JourneyResult:
    """Search for products and verify results are relevant."""
    steps: list[JourneyStep] = []
    session = requests.Session()

    # Authenticate if needed
    if config.auth_type == "nextauth" and config.any_user():
        user = config.any_user()
        try:
            csrf = session.get(f"{base_url}/api/auth/csrf", timeout=10).json().get("csrfToken", "")
            session.post(f"{base_url}/api/auth/callback/credentials", data={
                "email": user.email, "password": user.password,
                "csrfToken": csrf, "redirect": "false", "json": "true",
            }, timeout=10, allow_redirects=False)
        except Exception:
            pass

    # Step 1: Get products to know what to search for
    product_name = None
    for path in ["/api/products"]:
        try:
            r = session.get(f"{base_url}{path}", timeout=10)
            if r.status_code == 200:
                data = r.json()
                products = data if isinstance(data, list) else data.get("data") or data.get("products") or []
                if products and len(products) > 0:
                    product_name = products[0].get("name", "")
                    steps.append(JourneyStep(
                        action="get_product_name", detail=f"Found product: {product_name}", passed=True,
                    ))
                    break
        except Exception:
            pass

    if not product_name:
        steps.append(JourneyStep(action="get_product_name", detail="no products found", passed=False, error="catalog empty"))
        return JourneyResult(name="Search", description="Search products and verify results", passed=False, steps=steps, stopped_at="get_product_name")

    # Step 2: Search for first word of product name
    search_term = product_name.split()[0] if product_name else "test"
    for param in ["q", "search", "query"]:
        try:
            r = session.get(f"{base_url}/api/products", params={param: search_term}, timeout=10)
            if r.status_code == 200:
                data = r.json()
                results = data if isinstance(data, list) else data.get("data") or data.get("products") or []
                if isinstance(results, list) and len(results) < 20:  # filtered, not all products
                    found = any(search_term.lower() in json.dumps(p).lower() for p in results)
                    steps.append(JourneyStep(
                        action="search",
                        detail=f"Search '{search_term}' ({param}=) → {len(results)} results, target {'found' if found else 'not found'}",
                        passed=found,
                        error="" if found else f"search for '{search_term}' didn't find '{product_name}'",
                    ))
                    all_passed = all(s.passed for s in steps)
                    return JourneyResult(name="Search", description="Search products and verify results", passed=all_passed, steps=steps)
        except Exception:
            continue

    steps.append(JourneyStep(action="search", detail="no search param worked", passed=False, error="search not functional"))
    return JourneyResult(name="Search", description="Search products and verify results", passed=False, steps=steps)


def _test_persistence_journey(config: TestConfig, base_url: str) -> JourneyResult:
    """Verify data persists across sessions."""
    steps: list[JourneyStep] = []

    # Session 1: Create something
    s1 = requests.Session()
    if config.auth_type == "nextauth" and config.any_user():
        user = config.any_user()
        try:
            csrf = s1.get(f"{base_url}/api/auth/csrf", timeout=10).json().get("csrfToken", "")
            s1.post(f"{base_url}/api/auth/callback/credentials", data={
                "email": user.email, "password": user.password,
                "csrfToken": csrf, "redirect": "false", "json": "true",
            }, timeout=10, allow_redirects=False)
        except Exception:
            pass

    # Add to cart in session 1
    product_id = None
    try:
        r = s1.get(f"{base_url}/api/products", timeout=10)
        if r.status_code == 200:
            data = r.json()
            products = data if isinstance(data, list) else data.get("data") or data.get("products") or []
            if products:
                product_id = products[0].get("id")
    except Exception:
        pass

    if product_id:
        try:
            r = s1.post(f"{base_url}/api/cart", json={"productId": product_id, "quantity": 1}, timeout=10)
            steps.append(JourneyStep(
                action="session1_add_cart", detail=f"Added product {product_id} to cart ({r.status_code})",
                passed=r.status_code in (200, 201),
            ))
        except Exception as e:
            steps.append(JourneyStep(action="session1_add_cart", detail=str(e), passed=False, error=str(e)))

    # Session 2: Fresh login, check cart persists
    s2 = requests.Session()
    if config.auth_type == "nextauth" and config.any_user():
        user = config.any_user()
        try:
            csrf = s2.get(f"{base_url}/api/auth/csrf", timeout=10).json().get("csrfToken", "")
            s2.post(f"{base_url}/api/auth/callback/credentials", data={
                "email": user.email, "password": user.password,
                "csrfToken": csrf, "redirect": "false", "json": "true",
            }, timeout=10, allow_redirects=False)
        except Exception:
            pass

    try:
        r = s2.get(f"{base_url}/api/cart", timeout=10)
        if r.status_code == 200:
            data = r.json()
            items = data if isinstance(data, list) else data.get("data") or data.get("items") or []
            has_items = isinstance(items, list) and len(items) > 0
            steps.append(JourneyStep(
                action="session2_check_cart",
                detail=f"New session, cart has {len(items) if isinstance(items, list) else '?'} item(s)",
                passed=has_items,
                error="" if has_items else "cart empty after re-login — data not persisted",
            ))
    except Exception as e:
        steps.append(JourneyStep(action="session2_check_cart", detail=str(e), passed=False, error=str(e)))

    all_passed = all(s.passed for s in steps)
    return JourneyResult(
        name="Data Persistence", description="Cart data survives across sessions",
        passed=all_passed, steps=steps,
    )


def save_tier2_report(result: Tier2Result, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "product_dir": result.product_dir,
        "intent": result.intent,
        "base_url": result.base_url,
        "mode": result.mode,
        "score": result.score(),
        "journeys_tested": result.journeys_tested,
        "journeys_passed": result.journeys_passed,
        "journeys_failed": result.journeys_failed,
        "duration_s": result.duration_s,
        "journeys": [
            {
                "name": j.name,
                "description": j.description,
                "passed": j.passed,
                "stopped_at": j.stopped_at,
                "steps": [
                    {
                        "action": s.action,
                        "detail": s.detail,
                        "passed": s.passed,
                        "error": s.error,
                        "proof": {
                            "timestamp": s.proof.timestamp,
                            "request": s.proof.request,
                            "response": s.proof.response,
                        } if s.proof.timestamp else None,
                    }
                    for s in j.steps
                ],
            }
            for j in result.journeys
        ],
    }
    path.write_text(json.dumps(data, indent=2, default=str))


def save_tier2_markdown(result: Tier2Result, path: Path) -> None:
    lines = [
        "# Tier 2 Certification — User Journey Testing",
        "",
        f"> **Product:** `{result.product_dir}`",
        f"> **Mode:** {result.mode}",
        f"> **Journeys:** {result.journey_score()}",
        f"> **Steps:** {result.step_score()}",
        f"> **Duration:** {result.duration_s:.0f}s",
        "",
        "## What This Tests",
        "",
        "Multi-step user flows where each step depends on the previous step's output.",
        "Catches integration bugs that per-endpoint Tier 1 probes miss.",
        "If a step fails, the journey stops — downstream steps can't run.",
        "",
    ]

    for journey in result.journeys:
        icon = "✓" if journey.passed else "✗"
        lines.append(f"## {icon} {journey.name}")
        lines.append(f"_{journey.description}_")
        if journey.stopped_at:
            lines.append(f"**Stopped at:** {journey.stopped_at}")
        lines.append("")

        for step in journey.steps:
            step_icon = "✓" if step.passed else "✗"
            lines.append(f"- {step_icon} **{step.action}**: {step.detail}")
            if step.error:
                lines.append(f"  > ⚠ {step.error}")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## Scope",
        "",
        "Tier 2 tests connected flows, not individual endpoints.",
        "A 100% score means all flows complete end-to-end.",
        "It does not test visual rendering, performance, or accessibility.",
    ])

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
