"""Manage the project's `.gitignore` to exclude otto's runtime artifacts.

Otto's bookkeeping (queue.yml, state.json, worktrees/, otto_logs/) is
generated state — it doesn't belong in the user's repo. If we don't
auto-ignore it, the merge orchestrator's "working tree clean" check
flags every queued task as a dirty-tree precondition failure, and worse,
naive `git add .` from the user accidentally commits otto internals.

This module is idempotent. It only adds patterns that aren't already
matched by an existing line. Existing user content is preserved verbatim
(no reordering, no dedup of unrelated entries).

When the file is modified for the first time, the change is auto-committed
as a single `chore(otto): …` commit so the working tree stays clean for
subsequent merge operations. Without auto-commit, the new `.gitignore`
itself appears as untracked and trips `working_tree_clean()`.

Called from:
- `otto setup` (explicit init)
- `otto queue build|improve|certify|run` (first-touch init for users
  who skipped `otto setup`)
- `otto merge` (defensive: ensure clean-tree check passes for users
  who upgraded otto without re-running setup)
"""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger("otto.setup_gitignore")

OTTO_AUTO_COMMIT_MSG = "chore(otto): ignore runtime artifacts (.otto-queue, otto_logs, .worktrees)"

# Patterns appended under an `# Otto runtime` heading. Order matters only
# for cosmetics — leave grouped by origin (queue / worktree / logs).
OTTO_PATTERNS: tuple[str, ...] = (
    # Queue bookkeeping
    ".otto-queue.yml",
    ".otto-queue.yml.lock",
    ".otto-queue.lock",
    ".otto-queue-state.json",
    ".otto-queue-commands.jsonl",
    ".otto-queue-commands.jsonl.lock",
    # Worktrees the queue spawns
    ".worktrees/",
    # Per-build / per-task logs and proof of work
    "otto_logs/",
    # Watcher process logs (generated by `otto queue run`)
    ".watcher.log",
)

OTTO_HEADER = "# Otto runtime (auto-managed; safe to edit comments)"


def ensure_gitignore(project_dir: Path, *, auto_commit: bool = True) -> bool:
    """Append any missing otto patterns to ``.gitignore`` and (by default)
    auto-commit the change. Returns True iff the file was modified.

    Auto-commit happens only when (a) the file changed AND (b) project_dir is
    a git working tree AND (c) there are no other staged changes that would
    accidentally get bundled in. If the user already has staged changes, we
    write but don't commit and log a warning — the user's next merge will
    fail with the dirty-tree check, which is the correct fallback (we'd
    rather warn than silently bundle their work into a chore commit).
    """
    gi = project_dir / ".gitignore"
    existing_text = gi.read_text() if gi.exists() else ""
    existing_lines = existing_text.splitlines()
    existing_set = {line.strip() for line in existing_lines}

    missing = [p for p in OTTO_PATTERNS if p not in existing_set]
    if not missing:
        return False

    out_lines = list(existing_lines)
    if out_lines and out_lines[-1].strip() != "":
        out_lines.append("")
    if OTTO_HEADER not in existing_set:
        out_lines.append(OTTO_HEADER)
    out_lines.extend(missing)
    out_lines.append("")  # trailing newline

    new_text = "\n".join(out_lines)
    try:
        gi.write_text(new_text)
    except OSError as exc:
        logger.warning("could not update .gitignore at %s: %s", gi, exc)
        return False
    logger.info("added %d patterns to .gitignore: %s", len(missing), missing)

    if auto_commit:
        _maybe_commit_gitignore(project_dir, gi)

    return True


def _maybe_commit_gitignore(project_dir: Path, gi: Path) -> None:
    """Commit the .gitignore change if (a) we're in a git tree and (b) there
    are no other staged changes that would get bundled. Best-effort; failures
    are logged but never raised."""
    try:
        head = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=project_dir, capture_output=True, text=True, check=False,
        )
        if head.returncode != 0:
            return  # not a git repo
        # Check for any pre-existing staged changes (other than our .gitignore)
        diff_cached = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            cwd=project_dir, capture_output=True, text=True, check=False,
        )
        staged = [n for n in (diff_cached.stdout or "").splitlines() if n and n != ".gitignore"]
        if staged:
            logger.warning(
                "skipped auto-commit of .gitignore: other staged files present (%s); "
                "commit them yourself, then re-run otto",
                staged,
            )
            return
        subprocess.run(
            ["git", "add", str(gi.relative_to(project_dir))],
            cwd=project_dir, capture_output=True, text=True, check=True,
        )
        subprocess.run(
            ["git", "commit", "-q", "-m", OTTO_AUTO_COMMIT_MSG, "--", str(gi.relative_to(project_dir))],
            cwd=project_dir, capture_output=True, text=True, check=True,
        )
        logger.info("auto-committed .gitignore: %s", OTTO_AUTO_COMMIT_MSG)
    except subprocess.CalledProcessError as exc:
        logger.warning(
            "auto-commit of .gitignore failed (rc=%d): %s",
            exc.returncode, (exc.stderr or "").strip(),
        )
