"""Manage the project's `.gitignore` to exclude otto's runtime artifacts.

Otto's bookkeeping (queue.yml, state.json, worktrees/, otto_logs/) is
generated state — it doesn't belong in the user's repo. If we don't
auto-ignore it, the merge orchestrator's "working tree clean" check
flags every queued task as a dirty-tree precondition failure, and worse,
naive `git add .` from the user accidentally commits otto internals.

This module is idempotent. It only adds patterns that aren't already
matched by an existing line. Existing user content is preserved verbatim
(no reordering, no dedup of unrelated entries).

When the file is modified for the first time, the change is auto-committed
as a single `chore(otto): …` commit so the working tree stays clean for
subsequent merge operations. Without auto-commit, the new `.gitignore`
itself appears as untracked and trips `working_tree_clean()`.

Called from:
- `otto setup` (explicit init)
- `otto queue build|improve|certify|run` (first-touch init for users
  who skipped `otto setup`)
- `otto merge` (defensive: ensure clean-tree check passes for users
  who upgraded otto without re-running setup)
"""

from __future__ import annotations

import fnmatch
import logging
import subprocess
from pathlib import Path

logger = logging.getLogger("otto.setup_gitignore")

OTTO_AUTO_COMMIT_MSG = "chore(otto): ignore runtime artifacts (.otto-queue, otto_logs, .worktrees)"

# Patterns appended under an `# Otto runtime` heading. Order matters only
# for cosmetics — leave grouped by origin (queue / worktree / logs).
OTTO_PATTERNS: tuple[str, ...] = (
    # Queue bookkeeping
    ".otto-queue.yml",
    ".otto-queue.yml.lock",
    ".otto-queue.lock",
    ".otto-queue-state.json",
    ".otto-queue-commands.jsonl",
    ".otto-queue-commands.jsonl.processing",
    ".otto-queue-commands.jsonl.lock",
    ".otto-queue-commands.acks.jsonl",
    # Worktrees the queue spawns
    ".worktrees/",
    # Per-build / per-task logs and proof of work
    "otto_logs/",
    # Browser/audit evidence generated by Otto checks and audits
    "otto_artifacts/",
    # Watcher process logs (generated by `otto queue run`)
    ".watcher.log",
)

OTTO_HEADER = "# Otto runtime (auto-managed; safe to edit comments)"

# Common language/framework build artifacts that any reasonable project
# would want gitignored. Otto adds these so the merge orchestrator's
# "no new untracked files" validator doesn't bail when the conflict agent
# runs project tests (e.g. pytest creates __pycache__/, npm test creates
# node_modules/.cache, etc.).
COMMON_BUILD_ARTIFACT_PATTERNS: tuple[str, ...] = (
    # Python
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    ".pytest_cache/",
    ".venv/",
    "venv/",
    ".env/",
    ".coverage",
    "htmlcov/",
    "*.egg-info/",
    ".mypy_cache/",
    ".ruff_cache/",
    "*.db",
    "*.sqlite",
    "*.sqlite3",
    "instance/",
    # Node
    "node_modules/",
    ".npm/",
    # General build output
    "dist/",
    "build/",
    ".cache/",
    # IDE noise
    ".vscode/",
    ".idea/",
)
COMMON_HEADER = "# Common build artifacts (added by Otto so merge agent test runs don't trip validators)"


# Defence-in-depth: even if a project's .gitignore is incomplete or has
# been edited to drop these entries, callers checking "is the working
# tree user-dirty?" (JobDialog dirty-target preflight, merge preflight,
# W5-CRITICAL-1 untracked-aware merge block) must still classify these
# paths as Otto-owned and not user-owned. The fnmatch patterns below
# mirror OTTO_PATTERNS but use globbing semantics suitable for
# `git status --porcelain` output (which lists `??` paths verbatim).
OTTO_OWNED_DIRTY_PATTERNS: tuple[str, ...] = (
    ".otto-queue*",
    "otto_logs/*",
    "otto_logs",
    ".worktrees/*",
    ".worktrees",
    ".watcher.log",
    "_otto_build_logs",
    "_otto_build_logs/*",
    # Browser automation artifacts generated by Otto/audit/agent-browser
    # runs. They are evidence, not user source files.
    ".playwright-cli",
    ".playwright-cli/*",
    "otto_artifacts",
    "otto_artifacts/*",
    # V20: audit phase walks the running app and saves rendered HTML
    # snapshots like `__audit_home_body__.html`, `__audit_signup_body__.html`
    # next to the project root. They're Otto's own artifacts; if a user
    # cleans them up the next audit will recreate them. Don't flag dirty.
    "__audit_*.html",
    "__audit_*.json",
    "__audit_*.png",
    # V20: user-owned Otto inputs. `otto.yaml` and `intent.md` are
    # the project's Otto config and product spec; they sit at project
    # root and may legitimately exist untracked on first run (the
    # user authored them but never `git add`-ed). MC should not
    # show "dirty" + "Landing blocked" for these.
    "otto.yaml",
    "intent.md",
    # i2p pipeline writes session dirs under otto_logs/ already
    # covered, but also some pipelines drop a top-level `_session/`
    # alias (test fixtures); guard.
    "_session",
    "_session/*",
    ".otto",
    ".otto/*",
)


def is_otto_owned_path(path: str) -> bool:
    """Return True iff a working-tree path is one of Otto's runtime files.

    Used by the dirty-tree refusal layers (JobDialog preflight in
    ``serializers._project_is_user_dirty`` and the merge-action preflight
    in ``config.repo_preflight_issues``) to decide whether an untracked
    entry counts as user-owned (must block) or Otto-owned (must be
    tolerated).
    """
    norm = path.strip()
    while norm.startswith("./"):
        norm = norm[2:]
    norm = norm.rstrip("/")
    if not norm:
        return False
    for pattern in OTTO_OWNED_DIRTY_PATTERNS:
        bare = pattern.rstrip("/").rstrip("*").rstrip("/")
        if not bare:
            continue
        if fnmatch.fnmatch(norm, pattern):
            return True
        # Treat the bare prefix as covering descendants too — git's
        # porcelain reports an untracked directory itself (with a
        # trailing slash) without enumerating its children.
        if norm == bare or norm.startswith(bare + "/"):
            return True
        if fnmatch.fnmatch(norm, bare):
            return True
    return False


def git_porcelain_path(line: str) -> str:
    """Extract the working-tree path from a porcelain status row."""
    raw = line[3:] if len(line) > 3 else line
    if " -> " in raw:
        raw = raw.rsplit(" -> ", 1)[1]
    return raw.strip().strip('"')


def otto_owned_paths_from_porcelain(output: str) -> list[str]:
    """Return Otto-owned paths mentioned by `git status --porcelain` output."""
    paths: list[str] = []
    seen: set[str] = set()
    for line in output.splitlines():
        if not line.strip():
            continue
        path = git_porcelain_path(line)
        if path and path not in seen and is_otto_owned_path(path):
            seen.add(path)
            paths.append(path)
    return paths


def non_product_paths_from_porcelain(output: str) -> list[str]:
    """Return generated/runtime paths that must not be committed as product code."""
    paths: list[str] = []
    seen: set[str] = set()
    for line in output.splitlines():
        if not line.strip():
            continue
        path = git_porcelain_path(line)
        if not path or path in seen:
            continue
        if is_otto_owned_path(path) or is_common_build_artifact_path(path):
            seen.add(path)
            paths.append(path)
    return paths


def is_common_build_artifact_path(path: str) -> bool:
    """Return True for generated test/build/runtime artifacts Otto ignores.

    This is deliberately narrower than "any untracked file": it mirrors the
    common artifact patterns Otto writes into managed `.gitignore` files so
    stale resume checks and dirty-target checks do not block on files produced
    by pytest, Flask, SQLite-backed demos, or local build tools.
    """
    norm = path.strip()
    while norm.startswith("./"):
        norm = norm[2:]
    norm = norm.rstrip("/")
    if not norm:
        return False

    parts = Path(norm).parts
    name = parts[-1] if parts else norm
    for pattern in COMMON_BUILD_ARTIFACT_PATTERNS:
        pat = pattern.strip()
        if not pat:
            continue
        is_dir_pattern = pat.endswith("/")
        bare = pat.rstrip("/")
        if not bare:
            continue
        if is_dir_pattern:
            if any(fnmatch.fnmatch(part, bare) for part in parts):
                return True
            if fnmatch.fnmatch(norm, bare) or fnmatch.fnmatch(norm, bare + "/*"):
                return True
            continue
        if fnmatch.fnmatch(norm, pat) or fnmatch.fnmatch(name, pat):
            return True
    return False


def ensure_gitignore(project_dir: Path, *, auto_commit: bool = True) -> bool:
    """Append any missing otto patterns to ``.gitignore`` and (by default)
    auto-commit the change. Returns True iff the file was modified.

    Auto-commit happens only when (a) the file changed AND (b) project_dir is
    a git working tree AND (c) there are no other staged changes that would
    accidentally get bundled in. If the user already has staged changes, we
    write but don't commit and log a warning — the user's next merge will
    fail with the dirty-tree check, which is the correct fallback (we'd
    rather warn than silently bundle their work into a chore commit).
    """
    gi = project_dir / ".gitignore"
    existing_text = gi.read_text() if gi.exists() else ""
    existing_lines = existing_text.splitlines()
    existing_set = {line.strip() for line in existing_lines}

    missing_otto = [p for p in OTTO_PATTERNS if p not in existing_set]
    missing_common = [p for p in COMMON_BUILD_ARTIFACT_PATTERNS if p not in existing_set]
    if not missing_otto and not missing_common:
        return False

    out_lines = list(existing_lines)
    if out_lines and out_lines[-1].strip() != "":
        out_lines.append("")
    if missing_otto:
        if OTTO_HEADER not in existing_set:
            out_lines.append(OTTO_HEADER)
        out_lines.extend(missing_otto)
    if missing_common:
        if out_lines and out_lines[-1].strip() != "":
            out_lines.append("")
        if COMMON_HEADER not in existing_set:
            out_lines.append(COMMON_HEADER)
        out_lines.extend(missing_common)
    out_lines.append("")  # trailing newline
    missing = missing_otto + missing_common

    new_text = "\n".join(out_lines)
    try:
        gi.write_text(new_text)
    except OSError as exc:
        logger.warning("could not update .gitignore at %s: %s", gi, exc)
        return False
    logger.info("added %d patterns to .gitignore: %s", len(missing), missing)

    if auto_commit:
        _maybe_commit_gitignore(project_dir, gi)

    return True


def _maybe_commit_gitignore(project_dir: Path, gi: Path) -> None:
    """Commit the .gitignore change if (a) we're in a git tree and (b) there
    are no other staged changes that would get bundled. Best-effort; failures
    are logged but never raised."""
    try:
        head = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=project_dir, capture_output=True, text=True, check=False,
        )
        if head.returncode != 0:
            return  # not a git repo
        # Check for any pre-existing staged changes (other than our .gitignore)
        diff_cached = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            cwd=project_dir, capture_output=True, text=True, check=False,
        )
        staged = [n for n in (diff_cached.stdout or "").splitlines() if n and n != ".gitignore"]
        if staged:
            logger.warning(
                "skipped auto-commit of .gitignore: other staged files present (%s); "
                "commit them yourself, then re-run otto",
                staged,
            )
            return
        subprocess.run(
            ["git", "add", str(gi.relative_to(project_dir))],
            cwd=project_dir, capture_output=True, text=True, check=True,
        )
        subprocess.run(
            ["git", "commit", "-q", "-m", OTTO_AUTO_COMMIT_MSG, "--", str(gi.relative_to(project_dir))],
            cwd=project_dir, capture_output=True, text=True, check=True,
        )
        logger.info("auto-committed .gitignore: %s", OTTO_AUTO_COMMIT_MSG)
    except subprocess.CalledProcessError as exc:
        logger.warning(
            "auto-commit of .gitignore failed (rc=%d): %s",
            exc.returncode, (exc.stderr or "").strip(),
        )
